// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0eolXIexAp6z96IV4nDXn728gTAeUsN8',
    appId: '1:319897379984:web:038020c7020d7807b8a415',
    messagingSenderId: '319897379984',
    projectId: 'menta-32e34',
    authDomain: 'menta-32e34.firebaseapp.com',
    databaseURL: 'https://menta-32e34-default-rtdb.firebaseio.com',
    storageBucket: 'menta-32e34.appspot.com',
    measurementId: 'G-81LK5W7D0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWwjz3y38uDTNnY-fXp77uLDSZ6JCDnIE',
    appId: '1:319897379984:android:5737453f8fe25936b8a415',
    messagingSenderId: '319897379984',
    projectId: 'menta-32e34',
    databaseURL: 'https://menta-32e34-default-rtdb.firebaseio.com',
    storageBucket: 'menta-32e34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ5IPXBeK1FmGC9PccEzJBSPQEpF0pxt4',
    appId: '1:319897379984:ios:09428b2e41095e20b8a415',
    messagingSenderId: '319897379984',
    projectId: 'menta-32e34',
    databaseURL: 'https://menta-32e34-default-rtdb.firebaseio.com',
    storageBucket: 'menta-32e34.appspot.com',
    iosBundleId: 'com.example.courses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ5IPXBeK1FmGC9PccEzJBSPQEpF0pxt4',
    appId: '1:319897379984:ios:50813bc34a1546a2b8a415',
    messagingSenderId: '319897379984',
    projectId: 'menta-32e34',
    databaseURL: 'https://menta-32e34-default-rtdb.firebaseio.com',
    storageBucket: 'menta-32e34.appspot.com',
    iosBundleId: 'com.example.courses.RunnerTests',
  );
}
